### ISSUE TITLE
collapse_template() doesn't seem to work in an event

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALToolbox#63]
https://github.com/SuffolkLITLab/docassemble-ALToolbox/blob/6cd512484c006ae67f2dd075f905d2cb7d5cdcd5/docassemble/ALToolbox/misc.py#L106

```
AttributeError: 'str' object has no attribute 'instanceName'

History
Needed definition of al_sessions_snapshot_label at 0.00000s
Tried to ask question at 0.00008s

(from al_saved_sessions.yml)

id: save answer snapshot
# Save a copy
decoration: save
question: |
  Save an answer set
subquestion: |
  % if not user_logged_in():
  <div class="alert alert-danger fade show d-flex" role="alert">
  :exclamation-triangle: &nbsp;
  <div>
  You need to be signed in to save an answer set.
  </div>
  </div>
  
  ${ collapse_template("al_sessions_explain_answer_set_template") }
  
  ${ action_button_html(url_of('login'), label="Sign in", icon="sign-in-alt", size="md", color="primary") }
  % else:

  <div class="alert alert-info alert-dismissible fade show d-flex" role="alert">
  :info-circle: &nbsp;
  <div>
  You do not need to use this feature to save your progress. Your progress is saved
  automatically as you answer questions on this site.
  </div>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  
  ${ collapse_template("al_sessions_explain_answer_set_template") }
  
  #### Your progress
  You visited ${ all_variables(include_internal=True).get('_internal',{}).get('steps',1) }
  screens in "${ all_variables(special='titles').get('full') }" so far.
  
  % endif
fields:
  - Name your answer set: al_sessions_snapshot_label
    default: |      
      % if defined('users[0].name.first'):
      ${ comma_and_list(users.complete_elements()) }
      % if defined('other_parties[0].name.first'):
      v. ${ comma_and_list(other_parties.complete_elements()) }
      % endif
      % else:
      ${ all_variables(special='titles').get('full') }
      % if all_variables(special='titles').get('sub'):
      : ${ all_variables(special='titles').get('sub') }
      % endif
      % endif
    help: |
      Give this answer set a name you can remember later
continue button label: |
  :save: Save answer set
script: |
  <script>
  % if not user_logged_in():
    $(".da-field-buttons .btn-primary").attr("disabled", true);
    $(".da-form-group input").attr("disabled", true);
  % endif
  </script>  

[Show variables and values](https://apps-dev.suffolklitlab.org/vars?i=docassemble.playground10ALSaveSession%3Aal_question_test.yml)
Log

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7716, in assemble
    exec(run_process_action, user_dict)
  File "<code block>", line 1, in <module>
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/functions.py", line 3561, in process_action
    force_ask(*this_thread.current_info['arguments']['variables'])
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/functions.py", line 3293, in force_ask
    raise ForcedNameError(*the_pargs, user_dict=get_user_dict())
docassemble.base.error.ForcedNameError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 7646, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8075, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7862, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8558, in askfor
    return question.ask(user_dict, old_user_dict, the_x, iterators, missing_var, origMissingVariable)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 4975, in ask
    subquestion = self.subcontent.text(user_dict).rstrip()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 1427, in text
    return self.template.render(**the_user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/template.py", line 451, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/runtime.py", line 828, in _render
    _render_context(template, callable_, context, *args,
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7fa04cc65130", line 43, in render_body
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/ALToolbox/misc.py", line 114, in collapse_template
    the_id = re.sub(r"[^A-Za-z0-9]", "", template.instanceName)
AttributeError: 'str' object has no attribute 'instanceName'
```

**Comment by BryceStevenWilley** [comment]
This isn't actually accurate, it seems to work fine with event screens. Here's one working fine below:
```yaml
include:
  - docassemble.ALToolbox:collapse_template.yml
---
mandatory: True
code: |
  event_screen
---
template: my_templ
subject: Subject
content: |
  Longer content, in the drop down
---
event: event_screen
question: Hi
subquestion: |
  ${ collapse_template(my_templ) }
```
From your example, it looks like the issue is you passed the string of the template, not the template object itself. Not sure if there's a way to handle that within the `collapse_template` function, but it's probably a different issue though.
